export const ACTION_FETCH_USERS = 'user/ACTION_FETCH_USERS'
export const MUTATE_SET_USER_STATE = 'user/MUTATE_SET_USER_STATE'
export const MUTATE_UPDATE_USER_LIST = 'user/MUTATE_UPDATE_USER_LIST'
export const MUTATE_REMOVE_USER_FROM_LIST = 'user/MUTATE_REMOVE_USER_FROM_LIST'
export const GET_USER_STATE = 'user/GET_USER_STATE'

export const MUTATE_SET_APP_STATE = 'app/MUTATE_SET_APP_STATE'
export const GET_APP_STATE = 'app/GET_APP_STATE'
